### ISSUE TITLE
io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams addToActiveStreams SEVERE: Caught Throwable from listener onStreamActive.

### ISSUE THREAD

**Issue by juwens** [ButterCam/compose-jetbrains-theme#6]
I don't know why, but my grpc request does not work through the proxy.

```
Nov 09, 2021 10:59:44 AM io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams addToActiveStreams
SEVERE: Caught Throwable from listener onStreamActive.
java.lang.AssertionError
	at io.netty.handler.codec.http2.DefaultHttp2LocalFlowController$DefaultState.window(DefaultHttp2LocalFlowController.java:364)
	at io.netty.handler.codec.http2.DefaultHttp2LocalFlowController$DefaultState.<init>(DefaultHttp2LocalFlowController.java:358)
	at io.netty.handler.codec.http2.DefaultHttp2LocalFlowController$1.onStreamActive(DefaultHttp2LocalFlowController.java:101)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.addToActiveStreams(DefaultHttp2Connection.java:991)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.activate(DefaultHttp2Connection.java:946)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.activate(DefaultHttp2Connection.java:501)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:757)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:668)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders0(DefaultHttp2ConnectionEncoder.java:201)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:167)
	at io.kanro.mediator.proxy.http2.Http2GrpcServerHandler.onHeadersRead(Http2GrpcServerHandler.kt:91)
```

**Comment by devkanro** [comment]
Please create issue in [Mediator](https://github.com/ButterCam/Mediator)
